name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  
      - name: Build and push multi-arch Docker image
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx build --platform linux/amd64,linux/arm64 -t yourusername/yourimage:latest .
          docker buildx imagetools create yourusername/yourimage:latest --tag yourusername/yourimage --target manifest

      - name: Push multi-arch Docker image
        run: docker push yourusername/yourimage:latest
          