name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    environment: wrangler-discord-bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt large secret
        env:
          COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
        run: ./decrypt.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kipphulick/wrangler-image:latest
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TOKEN=${{ secrets.DISCORD_TOKEN }}
            CLIENT_ID=${{ secrets.CLIENT_ID }}
            SPOTIFY_ID=${{ secrets.SPOTIFY_ID }}
            SPOTIFY_SECRET=${{ secrets.SPOTIFY_SECRET }}
            DB_TOKEN=${{ secrets.DB_TOKEN }}
            SRA_KEY=${{ secrets.SRA_KEY }}
            SERP_KEY=${{ secrets.SERP_KEY }}