name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    environment: wrangler-discord-bot
    runs-on: ubuntu-latest
    steps:
      - name: Decode base64 secrets
        uses: actions/checkout@v2
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: echo $YOUTUBE_TOKEN | base64 -d > src/utils/secrets.js
  
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
          SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
          DB_TOKEN: ${{ secrets.DB_TOKEN }}
          SRA_KEY: ${{ secrets.SRA_KEY }}
          SERP_KEY: ${{ secrets.SERP_KEY }}
        
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kipphulick/wrangler-image:latest
          platforms: linux/arm64
        